### PR TITLE
Add Home station

### PR DESCRIPTION
**Pull request by Flydiverny**
This should probably have been split into 3 PRs buut anyway.
Unfortunately I don't speak german so added locales are only in english 🥲 

This adds a new feature called "Home station", which allows each player to setup a home station in the mod settings.

When pressing `H` the motorcar will replace the schedule with the home station as the only stop and toggle the train to automatic to get you home.

| When setup | When not setup | When setup with multiple surfaces | 
| -- | -- | -- | 
| image | image | image |

| Mod settings |
| --- |
| image |

----

Also adds an option to disable keeping the temporary stops when using the keep schedule option.

---

Finally adds a little fix for scaling autogenerated motorcar graphics for locomotives that don't use layers for pictures, like Angels Crawler train.

### CODE REVIEW

**Comment by S3bulon** [comment]
I merged it and fixed some stuff. Do you want to take a look at it before I merge it to master?

**Comment by S3bulon** [comment]
Btw: thanks for the contribution

**Comment by Flydiverny** [comment]
Additional changes seems like good fixes! Especially the icon support in the home station config, did run into that pretty soon but didn't get around to fixing it 😄 switching the separator makes sense

In the meanwhile I've run a fork on my own server, where I played around with some additional changes.
Adding an overlay image on generated motorcar items and some change to how the name is generated as I saw some issues on some items, not sure how solid those fixes are tho
https://github.com/Flydiverny/railway-motor-car/commit/213733e05623982c8f51a8b083bf5585506b198f

**Comment by S3bulon** [comment]
Good ideas, I reworked and integrated them into the home-branch.
Especially the dependency to flib - I prefer to keep it lightweight for users who do not use many mods.

**Pull request merged**
